### ISSUE TITLE
Conversion of MLprac2_2.Rnw to R markdown

### ISSUE THREAD

**Issue by phyleria** [vjcitn/MLInterfaces#8]
Hi @vjcitn 

 Would you be willing to accept another PR with the R Markdown
version of MLprac2_2.Rnw. I'll kindly ask you to
review and accept the pull request. 
I'm currently working on it, thank you.

**Comment by vjcitn** [comment]
Of course, let me know when ready.

**Comment by phyleria** [comment]
Thank you, I will.
